### ISSUE TITLE
Running on hydro

### ISSUE THREAD

**Issue by mhallak** [OTL/rqt_ez_publisher#13]
rosrun rqt_ez_publisher rqt_ez_publisher

Following exception:

michele@darpaws5:~$ rosrun rqt_ez_publisher rqt_ez_publisher
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/ez_publisher_widget.py", line 23, in add_slider_from_combo
    self.add_slider_by_text(str(self._combo.currentText()))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/ez_publisher_widget.py", line 90, in add_slider_by_text
    results = self._model.register_topic_by_text(text)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/ez_publisher_model.py", line 235, in register_topic_by_text
    self._add_publisher_if_not_exists(topic_name, message_class)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/ez_publisher_model.py", line 200, in _add_publisher_if_not_exists
    topic_name, message_class)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/publisher/topic_publisher_with_timer.py", line 13, in __init__
    topic_name, message_class)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/publisher/topic_fill_header_publisher.py", line 10, in **init**
    topic_name, message_class)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/publisher/topic_publisher.py", line 9, in **init**
    topic_name, message_class, queue_size=100)
TypeError: **init**() got an unexpected keyword argument 'queue_size'

And GUI displays only list of topics: 
topic(+data member) name ..... all clear
Nothing

**Comment by OTL** [comment]
Thanks for feedback!!

I guess old rospy version causes this.
current hydro rospy.Publisher has queue_size option for **init**().

http://docs.ros.org/hydro/api/rospy/html/rospy.topics.Publisher-class.html

Could you tell me the version of rospy?
At least, 1.10.2 support this.

$ dpkg -s ros-hydro-rospy | grep Version

If you can, please apt-get update && apt-get upgrade.

**Comment by mhallak** [comment]
Hi!
Sorry for the delay of my answer.
Indeed, the version of rospy that I use is 
**_Version: 1.9.50-0precise-20131015-1940-+0000**_
and therefore lower than 1.10.
Unfortunately I cannot upgrade for now because I have no time right now to hack problems that might occur following the update...:+(

**Comment by OTL** [comment]
Uhhm, it is very easy to solve the problem.
if you reomve ", queue_size=100" from 
/opt/ros/hydro/lib/python2.7/dist-packages/rqt_ez_publisher/publisher/topic_publisher.py:L6.

but i does not recommend to do this. Please upgrade!

**Comment by mhallak** [comment]
Thanks for the tip!!!!!
