### ISSUE TITLE
--slider-file option fail in indigo

### ISSUE THREAD

**Issue by OTL** [OTL/rqt_ez_publisher#16]
ogura@smilebot-beta1:~$ rosrun rqt_ez_publisher rqt_ez_publisher --slider-file aa
PluginManager._load_plugin() could not load plugin "rqt_ez_publisher/EzPublisher":
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 98, in load
    self._load()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 94, in load
    return class_ref(plugin_context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_ez_publisher/ez_publisher_plugin.py", line 33, in __init__
    load_from_file(args.slider_file)
NameError: global name 'load_from_file' is not defined

**Comment by OTL** [comment]
fixed
