### ISSUE TITLE
uint8 type treated as string

### ISSUE THREAD

**Issue by jbwillis** [OTL/rqt_ez_publisher#30]
I am writing to a topic that has an array of type uint8 in it. When I adjust the slider, I get the following error message. It appears that python is handling the uint8 array as an array of strings. When I change the datatype of the array to uint32, I no longer get this error.
Here is the traceback:
```
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_ez_publisher/widget/int_value_widget.py", line 17, in slider_changed
    self.publish_value(value)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_ez_publisher/widget/value_widget.py", line 73, in publish_value
    self._array_index, value)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_ez_publisher/ez_publisher_model.py", line 56, in set_msg_attribute_value
    array[array_index] = value
TypeError: 'str' object does not support item assignment
```

And here is the message definition:
```
# Auxilliary Override Command Message

# Command Types
uint8 AUX_COMMAND_DISABLED = 0
uint8 AUX_COMMAND_SERVO = 1
uint8 AUX_COMMAND_MOTOR = 2

Header header
uint8[14] type_array
float32[14] values
```

**Comment by OTL** [comment]
I uploaded the patch to solve this.
03b1c0aeca4f379e2d4adbe965f16a6b3e004a05

Would you try it?

**Comment by jbwillis** [comment]
This worked properly, thank you.

**Comment by OTL** [comment]
Thank you for giving good feedbacks!
